name: Test

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: 'Test with ${{ matrix.os }}, Node.js v${{ matrix.node }}'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: ['20.12.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
        if: runner.os == 'Linux'
      - run: xvfb-run -a npm run test
        if: runner.os == 'Linux'
      - run: npm run test
        if: runner.os != 'Linux'
